fix bugs - helper text copy ingress ip & edit preinjected file & prob…
kalmhq/kalm pull request #192
Opened 2020-10-10 11:21 UTC by GonGH-E

…es fields validate

2020-10-10 16:13 UTC, davidqhr requested changes

2020-10-10 16:13 UTC, davidqhr commented on frontend/src/forms/ComponentLike/Probes.tsx
> -              validate={ValidatorRequired}
Port is a required field.

2020-10-10 16:13 UTC, davidqhr commented on frontend/src/forms/ComponentLike/Probes.tsx
> -              validate={ValidatorRequired}
You should check each field carefully.

2020-10-10 16:20 UTC, davidqhr commented on frontend/src/forms/ComponentLike/Probes.tsx
>                placeholder="/healthy"
This field need a parse attribute. If it's not blank, it should have prefix "/".

2020-10-10 16:21 UTC, davidqhr commented on frontend/src/forms/ComponentLike/Probes.tsx
> -              validate={validateHostWithWildcardPrefix}
Why delete this validator? Even this field is optional, you should also consider to validate context when it's not empty.

2020-10-13 02:20 UTC, GonGH-E commented
@davidqhr

2021-02-24 03:03 UTC, closed without merging